image_path = "./images/"

[[users]]
name = "Michael"
port = 12345

[[users]]
name = "Fabian"
port = 12346

[[users]]
name = "Can"
port = 12347

[[users]]
name = "Jin"
port = 12348

[[users]]
name = "Burim"
port = 12349