[network]
broadcast_ip = "192.168.2.255"
whoisport = 4000
buffer_size = 8192

[storage]
imagepath = "./bilder/"
bild_pfad = "./bilder/"

[features]
autoreply_enabled = false
autoreply = "Ich bin gerade nicht da. Schicke mir trotzdem eine Nachricht!"

[[users]]
name = "Michael"
handle = "Michael"
host_ip = "192.168.2.205"
port = 12345
ipc_port = 17345
image_ipc_port = 18045

# Weitere Benutzer (auf anderen Rechnern)
[[users]]
name = "Fabian"
handle = "Fabian"
host_ip = "192.168.2.209"  # IP vom zweiten PC (z. B. Laptop)
port = 12346
ipc_port = 17346
image_ipc_port = 18046

[[users]]
name = "Can"
handle = "Can"
host_ip = "192.168.2.209"
port = 12347
ipc_port = 17347
image_ipc_port = 18047
<<<<<<< HEAD
=======

[[users]]
name = "Jin"
handle = "Jin"
host_ip = "127.0.0.1"
port = 12348
ipc_port = 17348
image_ipc_port = 18048

[[users]]
name = "Burim"
handle = "Burim"
host_ip = "127.0.0.1"
port = 12349
ipc_port = 17349
image_ipc_port = 18049
>>>>>>> 512995f (Sprachlich vereinheitlicht)
