[network]
broadcast_ip = "192.168.2.255"
whoisport = 4000
buffer_size = 8192

[storage]
imagepath = "./bilder/"
bild_pfad = "./bilder/"

[features]
autoreply_enabled = false
autoreply = "Ich bin gerade nicht da. Schicke mir trotzdem eine Nachricht!"

[[users]]
id = 1
name = "Michael"
handle = "Michael"
host_ip = "192.168.2.205"
port = 12345
ipc_port = 17345
image_ipc_port = 18045

[[users]]
id = 2
name = "Fabian"
handle = "Fabian"
host_ip = "192.168.2.209"
port = 12346
ipc_port = 17346
image_ipc_port = 18046

[[users]]
id = 3
name = "Can"
handle = "Can"
host_ip = "192.168.2.209"
port = 12347
ipc_port = 17347
image_ipc_port = 18047